### ISSUE TITLE
Интересно!

### ISSUE THREAD

**Issue by FantomSmert** [ThomasAlvenin/Pterodactyl-ThomasVM#1]
Привет друг! Отличная идея, но у меня возник вопрос, а как установить это на панель?

**Comment by ThomasAlvenin** [comment]
> 

Hi! You cant install this as an EGG for Pterodactyl if that is what you want.

This is just a bypass for install Debian 10 on a Node.js hosting on Pterodactyl.

I still need to add some FAQ's, etc.

**Comment by FantomSmert** [comment]
Окей!

**Comment by Gaminghosting** [comment]
please how to install from egg
